---
functional:
  - Пользователь должен иметь возможность зарегистрироваться с помощью электронной почты
  - Зарегистрированный пользователь должен иметь возможность войти в аккаунт с помощью электронной почты
  - Пользователь должен иметь возможность войти в аккаунт, используя свой аккаунт на GitHub
  - Пользователь должен иметь возможность войти в аккаунт, используя свой аккаунт в Discord
  - Пользователь должен иметь возможность редактировать свой профиль, имя, аватар
  - Пользователь должен иметь возможность выбирать язык, на котором он хочет решать задачи
  - Пользователь должен иметь возможность создать игру с ботом
  - Пользователь должен иметь возможность создать игру с другом
  - Пользователь должен иметь возможность создать игру со случайным пользователем
  - Пользователь должен иметь возможность выбрать уровень сложности игры
  - Пользователь должен иметь возможность выбрать задачу (тему) игры
  - Пользователь должен иметь возможность присоединиться к игре, созданной другим пользователем
  - Пользователь должен иметь возможность принять участие в игре
  - Пользователь должен иметь возможность получать очки рейтинга
  - Пользователь должен иметь возможность добавлять собственные задачи
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь расширение для браузера
implicit:
  - Сайт должен иметь интуитивный и понятный дизайн
  - Сайт должен иметь чат или иное пространство для создания и поддержки атмосферы коммьюнити
  - Сайт должен иметь систему уведомлений о предстоящих играх/турнирах
  - Сайт должен иметь систему уведомлений о приглашении на участие в игре
  - Сайт должен поддерживать мультиязычность
  - Сайт должен предоставлять возможность связаться со службой поддержки
